from retail.registry import STORE_GROUP, list_stores

NEW_STORES = {
    "acer": ("tecnologia", "shopify"),
    "alisha": ("belleza", "shopify"),
    "aquitaine": ("belleza", "shopify"),
    "backonline": ("tecnologia", "shopify"),
    "bazhars": ("hogar", "shopify"),
    "bbqgrill": ("hogar", "vtex"),
    "beautybox": ("belleza", "shopify"),
    "befoods": ("otros", "shopify"),
    "bestmart": ("tecnologia", "shopify"),
    "bfresh": ("hogar", "shopify"),
    "bix": ("hogar", "shopify"),
    "blackbubba": ("moda", "shopify"),
    "blustore": ("tecnologia", "shopify"),
    "bosscamp": ("deporte", "shopify"),
    "boston": ("otros", "magento"),
    "brooks": ("moda", "magento"),
    "bsoul": ("moda", "shopify"),
    "babyrosen": ("infantil", "magento"),
    "canadienne": ("moda", "vtex"),
    "chileperfume": ("belleza", "woocommerce"),
    "cscalzado": ("calzado", "shopify"),
    "dacsa": ("otros", "woocommerce"),
    "dib": ("hogar", "shopify"),
    "dimarine": ("deporte", "vtex"),
    "dolly": ("moda", "vtex"),
    "ebest": ("tecnologia", "magento"),
    "ecofarmacias": ("farmacias", "woocommerce"),
    "electrolux": ("hogar", "vtex"),
    "extravirgen": ("gastronomia", "shopify"),
    "fullsublimacion": ("otros", "shopify"),
    "glowup": ("infantil", "shopify"),
    "gutenbrew": ("gastronomia", "shopify"),
    "hifi": ("musica", "shopify"),
    "himalaya": ("hogar", "shopify"),
    "hit": ("moda", "vtex"),
    "hohos": ("hogar", "woocommerce"),
    "honutrition": ("belleza", "shopify"),
    "huentelauquen": ("gastronomia", "woocommerce"),
    "imahe": ("hogar", "shopify"),
    "ironside": ("deporte", "shopify"),
    "jansport": ("moda", "vtex"),
    "japijane": ("belleza", "shopify"),
    "jayson": ("calzado", "magento"),
    "kallfu": ("hogar", "shopify"),
    "kayser": ("moda", "shopify"),
    "keds": ("calzado", "vtex"),
    "keter": ("hogar", "shopify"),
    "kidsclub": ("infantil", "shopify"),
    "lasilleria": ("hogar", "woocommerce"),
    "maisonniche": ("belleza", "shopify"),
    "mamasmateas": ("infantil", "shopify"),
    "marmot": ("deporte", "magento"),
    "marsella": ("ferreteria", "vtex"),
    "maxservice": ("calzado", "vtex"),
    "merjet": ("relojeria", "shopify"),
    "mifotopro": ("tecnologia", "woocommerce"),
    "milurugs": ("hogar", "shopify"),
    "mimbral": ("ferreteria", "vtex"),
    "mohicano": ("moda", "shopify"),
    "mormaii": ("deporte", "vtex"),
    "mueblesterrazas": ("hogar", "woocommerce"),
    "multimarcas": ("belleza", "shopify"),
    "mundoaromas": ("belleza", "shopify"),
    "newman": ("moda", "vtex"),
    "patioferretero": ("ferreteria", "shopify"),
    "potros": ("moda", "magento"),
    "prune": ("moda", "magento"),
    "retailcl": ("retail", "shopify"),
    "roly": ("moda", "magento"),
    "rutadiferente": ("deporte", "shopify"),
    "saideep": ("belleza", "shopify"),
    "singolare": ("moda", "shopify"),
    "sleve": ("tecnologia", "shopify"),
    "solong": ("moda", "shopify"),
    "teh": ("ferreteria", "shopify"),
    "tiendacopec": ("retail", "shopify"),
    "tiresimport": ("otros", "woocommerce"),
    "vanbeek": ("ferreteria", "shopify"),
    "vesper": ("belleza", "shopify"),
    "viuty": ("belleza", "woocommerce"),
    "volkanica": ("deporte", "shopify"),
    "wayu": ("hogar", "shopify"),
    "yonex": ("deporte", "shopify"),
}

KEEP = ("cheflab", "infanti", "tusmascotas", "ripley", "tottus", "salcobrand", "casaroyal", "mercadolibre", "ahumada")


def test_directorio_batch4_ids_unicos_y_agrupados():
    specs = {spec.id: spec for spec in list_stores()}
    assert len(specs) == len(list_stores())
    for store_id in KEEP:
        assert store_id in specs, store_id
    for store_id, (group, platform) in NEW_STORES.items():
        assert store_id in specs, store_id
        assert STORE_GROUP[store_id] == group
        assert specs[store_id].platform == platform
        assert specs[store_id].group in {None, group}
        assert group in {
            "retail",
            "farmacias",
            "supermercados",
            "gastronomia",
            "ferreteria",
            "musica",
            "belleza",
            "calzado",
            "deporte",
            "moda",
            "infantil",
            "hogar",
            "tecnologia",
            "relojeria",
            "otros",
        }
