from __future__ import annotations

import importlib
import pkgutil
from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from retail.base import StoreClient

_CLIENTS: dict[str, type[StoreClient]] = {}
_SPECS: dict[str, StoreSpec] = {}
_LOADED = False


GROUP_TITLES: dict[str, str] = {
    "retail": "Retail",
    "farmacias": "Farmacias",
    "supermercados": "Supermercados",
    "gastronomia": "Gastronomía",
    "ferreteria": "Ferretería",
    "musica": "Música",
    "belleza": "Belleza",
    "calzado": "Calzado",
    "deporte": "Deporte",
    "moda": "Moda",
    "infantil": "Infantil",
    "hogar": "Hogar",
    "tecnologia": "Tecnología",
    "libreria": "Librería",
    "juguetes": "Juguetes",
    "opticas": "Ópticas",
    "relojeria": "Relojería",
    "autos": "Autos",
    "otros": "Otros",
}
GROUP_ORDER = tuple(GROUP_TITLES)
STORE_GROUP: dict[str, str] = {
    "falabella": "retail",
    "paris": "retail",
    "ripley": "retail",
    "mercadolibre": "retail",
    "lider": "supermercados",
    "tottus": "supermercados",
    "unimarc": "supermercados",
    "alvi": "supermercados",
    "cugat": "supermercados",
    "ahumada": "farmacias",
    "cruzverde": "farmacias",
    "salcobrand": "farmacias",
    "drsimi": "farmacias",
    "sodimac": "ferreteria",
    "easy": "ferreteria",
    "construplaza": "ferreteria",
    "prat": "ferreteria",
    "weitzler": "ferreteria",
    "audiomusica": "musica",
    "casaroyal": "retail",
    "promusic": "musica",
    "dbs": "belleza",
    "sallybeauty": "belleza",
    "bodyshop": "belleza",
    "eliteperfumes": "belleza",
    "loccitane": "belleza",
    "lush": "belleza",
    "pichara": "belleza",
    "silkperfumes": "belleza",
    "preunic": "belleza",
    "azaleia": "calzado",
    "cardinale": "calzado",
    "converse": "calzado",
    "crocs": "calzado",
    "hushpuppies": "calzado",
    "vans": "calzado",
    "dcshoes": "calzado",
    "nike": "deporte",
    "doite": "deporte",
    "lippi": "deporte",
    "sparta": "deporte",
    "allnutrition": "deporte",
    "andesgear": "deporte",
    "asics": "deporte",
    "bikehouse": "deporte",
    "hakahonu": "deporte",
    "head": "deporte",
    "mammut": "deporte",
    "merrell": "deporte",
    "newbalance": "deporte",
    "nutrapharm": "deporte",
    "oxford": "deporte",
    "patagonia": "deporte",
    "puma": "deporte",
    "reebok": "deporte",
    "salomon": "deporte",
    "sportika": "deporte",
    "supletech": "deporte",
    "thenorthface": "deporte",
    "underarmour": "deporte",
    "dellanatura": "farmacias",
    "atika": "ferreteria",
    "budnik": "ferreteria",
    "mk": "ferreteria",
    "stretto": "ferreteria",
    "totaltools": "ferreteria",
    "adagio": "gastronomia",
    "cafehaiti": "gastronomia",
    "lavinoteca": "gastronomia",
    "marleycoffee": "gastronomia",
    "mundovino": "gastronomia",
    "wineclub": "gastronomia",
    "santaritaonline": "gastronomia",
    "varsovienne": "gastronomia",
    "descorcha": "gastronomia",
    "piwen": "gastronomia",
    "tika": "gastronomia",
    "fashionspark": "moda",
    "intime": "moda",
    "amphora": "moda",
    "bananarepublic": "moda",
    "calvinklein": "moda",
    "dockers": "moda",
    "ellus": "moda",
    "kipling": "moda",
    "levis": "moda",
    "lounge": "moda",
    "trial": "moda",
    "colloky": "infantil",
    "bebesit": "infantil",
    "ficcus": "infantil",
    "limonada": "infantil",
    "opaline": "infantil",
    "ikea": "hogar",
    "rosen": "hogar",
    "cannon": "hogar",
    "tiendaflores": "hogar",
    "byp": "hogar",
    "flex": "hogar",
    "interdesign": "hogar",
    "kitchencenter": "hogar",
    "mashini": "hogar",
    "medular": "hogar",
    "oster": "hogar",
    "simplepuro": "hogar",
    "thomas": "hogar",
    "tramontina": "hogar",
    "betterlife": "hogar",
    "janome": "hogar",
    "pcfactory": "tecnologia",
    "belkin": "tecnologia",
    "centrale": "tecnologia",
    "migo": "tecnologia",
    "motorola": "tecnologia",
    "movistar": "tecnologia",
    "entel": "tecnologia",
    "antartica": "libreria",
    "artenostro": "libreria",
    "contrapunto": "libreria",
    "ferialibro": "libreria",
    "torre": "libreria",
    "mundotransfer": "libreria",
    "maui": "moda",
    "ripcurl": "moda",
    "volcom": "moda",
    "gap": "moda",
    "ferouch": "moda",
    "perryellis": "moda",
    "tommy": "moda",
    "hugoboss": "moda",
    "guess": "moda",
    "speedo": "deporte",
    "needle": "musica",
    "ansaldo": "juguetes",
    "toyng": "juguetes",
    "piedrabruja": "juguetes",
    "catalonia": "libreria",
    "nacional": "libreria",
    "etienne": "belleza",
    "petrizzio": "belleza",
    "fdv": "hogar",
    "amesti": "ferreteria",
    "dartel": "ferreteria",
    "liquimoly": "otros",
    "weplay": "juguetes",
    "gmo": "opticas",
    "econopticas": "opticas",
    "opv": "opticas",
    "schilling": "opticas",
    "mosso": "relojeria",
    "swarovski": "relojeria",
    "chileautos": "autos",
    "autocosmos": "autos",
    "knasta": "retail",
    "dondelanegra": "gastronomia",
    "masisa": "hogar",
    "dimarsa": "retail",
    "hites": "retail",
    "privilege": "moda",
    "edelbrock": "moda",
    "fensa": "hogar",
    "indumac": "hogar",
    "homemobili": "hogar",
    "thorben": "hogar",
    "stoked": "deporte",
    "hp": "tecnologia",
    "garmin": "tecnologia",
    "productosdelujo": "belleza",
    "nooki": "belleza",
    "cosmetic": "belleza",
    "lodoro": "belleza",
    "vadell": "juguetes",
    "playmore": "juguetes",
    "apro": "ferreteria",
    "safetystore": "ferreteria",
    "braloy": "otros",
    "block": "calzado",
    "pesaschile": "deporte",
    "mennt": "moda",
    "starsex": "belleza",
    "azedan": "otros",
    "scaldasonno": "hogar",
    "fabricadevelas": "hogar",
    "zagg": "tecnologia",
    "juanvaldez": "gastronomia",
    "daher": "otros",
    "neumax": "otros",
    "thelab": "opticas",
    "vincenzi": "hogar",
    "sharkninja": "hogar",
    "atakama": "deporte",
    "nuvac": "hogar",
    "mademsa": "hogar",
    "toyotomi": "hogar",
    "vitepal": "ferreteria",
    "trek": "deporte",
    "fox": "deporte",
    "acqui": "hogar",
    "americaneagle": "moda",
    "arrow": "moda",
    "calu": "moda",
    "cheflab": "hogar",
    "coleman": "deporte",
    "delsey": "moda",
    "dermotienda": "belleza",
    "dolcegusto": "gastronomia",
    "dominame": "belleza",
    "domotiz": "tecnologia",
    "dpgoutlet": "moda",
    "ecook": "gastronomia",
    "etchile": "tecnologia",
    "florsheim": "calzado",
    "form": "hogar",
    "hardwork": "moda",
    "hitway": "musica",
    "ilgioco": "moda",
    "infanti": "infantil",
    "iochile": "moda",
    "ivmedical": "belleza",
    "kaltemp": "hogar",
    "kannu": "deporte",
    "kayaunite": "deporte",
    "kitchenhouse": "hogar",
    "kotting": "moda",
    "larelojeria": "relojeria",
    "lechepalpelo": "belleza",
    "lenceria": "moda",
    "lineatre": "moda",
    "magriffe": "moda",
    "mates": "gastronomia",
    "mayordent": "belleza",
    "mcgregor": "moda",
    "misjoyas": "moda",
    "outletdelcafe": "gastronomia",
    "passol": "ferreteria",
    "pethome": "otros",
    "petvet": "otros",
    "pilgrim": "moda",
    "polyphonik": "musica",
    "pumasafety": "ferreteria",
    "pyk": "otros",
    "rapsodia": "moda",
    "razaspet": "otros",
    "relan": "hogar",
    "salmonmarket": "gastronomia",
    "santiagoperfumes": "belleza",
    "softys": "hogar",
    "sokobox": "belleza",
    "spazzio": "hogar",
    "sportingbrands": "deporte",
    "steelpro": "ferreteria",
    "tecnored": "ferreteria",
    "theline": "moda",
    "totto": "moda",
    "treck": "ferreteria",
    "tusmascotas": "otros",
    "velez": "moda",
    "ventus": "hogar",
    "wados": "moda",
    "womensecret": "moda",
    "worbee": "tecnologia",
    "yauras": "belleza",
    "zoy": "hogar",
    "acer": "tecnologia",
    "alisha": "belleza",
    "aquitaine": "belleza",
    "backonline": "tecnologia",
    "bazhars": "hogar",
    "bbqgrill": "hogar",
    "beautybox": "belleza",
    "befoods": "otros",
    "bestmart": "tecnologia",
    "bfresh": "hogar",
    "bix": "hogar",
    "blackbubba": "moda",
    "blustore": "tecnologia",
    "bosscamp": "deporte",
    "boston": "otros",
    "brooks": "moda",
    "bsoul": "moda",
    "babyrosen": "infantil",
    "canadienne": "moda",
    "chileperfume": "belleza",
    "cscalzado": "calzado",
    "dacsa": "otros",
    "dib": "hogar",
    "dimarine": "deporte",
    "dolly": "moda",
    "ebest": "tecnologia",
    "ecofarmacias": "farmacias",
    "electrolux": "hogar",
    "extravirgen": "gastronomia",
    "fullsublimacion": "otros",
    "glowup": "infantil",
    "gutenbrew": "gastronomia",
    "hifi": "musica",
    "himalaya": "hogar",
    "hit": "moda",
    "hohos": "hogar",
    "honutrition": "belleza",
    "huentelauquen": "gastronomia",
    "imahe": "hogar",
    "ironside": "deporte",
    "jansport": "moda",
    "japijane": "belleza",
    "jayson": "calzado",
    "kallfu": "hogar",
    "kayser": "moda",
    "keds": "calzado",
    "keter": "hogar",
    "kidsclub": "infantil",
    "lasilleria": "hogar",
    "maisonniche": "belleza",
    "mamasmateas": "infantil",
    "marmot": "deporte",
    "marsella": "ferreteria",
    "maxservice": "calzado",
    "merjet": "relojeria",
    "mifotopro": "tecnologia",
    "milurugs": "hogar",
    "mimbral": "ferreteria",
    "mohicano": "moda",
    "mormaii": "deporte",
    "mueblesterrazas": "hogar",
    "multimarcas": "belleza",
    "mundoaromas": "belleza",
    "newman": "moda",
    "patioferretero": "ferreteria",
    "potros": "moda",
    "prune": "moda",
    "retailcl": "retail",
    "roly": "moda",
    "rutadiferente": "deporte",
    "saideep": "belleza",
    "singolare": "moda",
    "sleve": "tecnologia",
    "solong": "moda",
    "teh": "ferreteria",
    "tiendacopec": "retail",
    "tiresimport": "otros",
    "vanbeek": "ferreteria",
    "vesper": "belleza",
    "viuty": "belleza",
    "volkanica": "deporte",
    "wayu": "hogar",
    "yonex": "deporte",
}


@dataclass(frozen=True, slots=True)
class StoreSpec:
    id: str
    title: str
    site: str
    sort_map: dict[str, str]
    category_help: str
    extra_category: bool = False
    platform: str | None = None
    group: str | None = None


def group_of(store_id: str, override: str | None = None) -> tuple[str, str, int]:
    key = (override or STORE_GROUP.get(store_id) or "otros").lower()
    if key not in GROUP_TITLES:
        key = "otros"
    return key, GROUP_TITLES[key], GROUP_ORDER.index(key)


def register(spec: StoreSpec) -> Callable[[type[StoreClient]], type[StoreClient]]:
    def decorator(cls: type[StoreClient]) -> type[StoreClient]:
        cls.spec = spec
        _CLIENTS[spec.id] = cls
        _SPECS[spec.id] = spec
        return cls

    return decorator


def get_client(store_id: str, **kwargs):
    _ensure_loaded()
    key = store_id.lower().strip()
    if key not in _CLIENTS:
        available = ", ".join(sorted(_CLIENTS))
        raise ValueError(f"Tienda desconocida: {store_id}. Disponibles: {available}")
    return _CLIENTS[key](**kwargs)


def list_stores() -> list[StoreSpec]:
    _ensure_loaded()
    return [spec for _, spec in sorted(_SPECS.items())]


def load_sources() -> None:
    """Importa cada módulo de retail.sources para ejecutar @register."""
    import retail.sources as package

    for module in pkgutil.iter_modules(package.__path__):
        if module.name.startswith("_"):
            continue
        importlib.import_module(f"{package.__name__}.{module.name}")


def _ensure_loaded() -> None:
    global _LOADED
    if _LOADED:
        return
    load_sources()
    _LOADED = True
